---
logstash_forwarder_logstash_server: 45.56.117.106
logstash_forwarder_logstash_server_port: 5000

logstash_ssl_dir: /etc/pki/tls/certs
logstash_forwarder_ssl_certificate_file: logstash-forwarder.crt

logstash_forwarder_files:
  - paths:
      - /var/log/syslog
      - /var/log/auth.log
    fields:
      type: syslog
      hostip: "{{ ansible_eth0.ipv4.address }}"
      hostname: "{{ ansible_hostname }}"
      

  - paths:
      - /var/log/nginx/access.log
    fields:
      type: nginx-access
      hostip: "{{ ansible_eth0.ipv4.address }}"
      hostname: "{{ ansible_hostname }}"
       

  - paths:
      - /var/log/nginx/error.log
    fields:
      type: nginx-error
      hostip: "{{ ansible_eth0.ipv4.address }}"
      hostname: "{{ ansible_hostname }}"


  - paths:
      - /var/log/mysql/*.log
    fields:
      type: mysql
      hostip: "{{ ansible_eth0.ipv4.address }}"
      hostname: "{{ ansible_hostname }}"


  - paths:
      - /var/log/apache2/error.log
      - /var/log/apache2/access.log
    fields:
      type: apache2
      hostip: "{{ ansible_eth0.ipv4.address }}"
      hostname: "{{ ansible_hostname }}"


  - paths:
      - /var/log/redis/*.log
    fields:
      type: redis
      hostip: "{{ ansible_eth0.ipv4.address }}"
      hostname: "{{ ansible_hostname }}"


  - paths:
      - /var/log/uwsgi/*.log
    fields:
      type: uwsgi
      hostip: "{{ ansible_eth0.ipv4.address }}"
      hostname: "{{ ansible_hostname }}"


  - paths:
      - /var/log/mongodb/*.log
    fields:
      type: mongodb
      hostip: "{{ ansible_eth0.ipv4.address }}"
      hostname: "{{ ansible_hostname }}"
      nodename: "{{ ansible_nodename }}"

  - paths:
      - /var/log/haproxy/*.log
    fields:
      type: haproxy
      hostip: "{{ ansible_eth0.ipv4.address }}"
      hostname: "{{ ansible_hostname }}"


  - paths:
      - /var/log/upstart/xandar.log
      - /var/log/upstart/infinity.log
      - /var/log/upstart/starlord.log
    fields:
      type: upstart
      hostip: "{{ ansible_eth0.ipv4.address }}"
      hostname: "{{ ansible_hostname }}"




  # To add more sets of files...
  # - paths:
  #     - /var/log/boot.log
  #   fields:
  #     type: syslog
